import type { HeroDiscoveryData } from "./model";

export const HERO_DISCOVERY_MOCK: HeroDiscoveryData = {
  discoverySearchLabel: "Find a destination",
  discoverySearchPlaceholder: "Search Phu Quoc, Sa Pa, Hoi An...",
  discoverySearchActionLabel: "Search",
  discoveryQuickFiltersLabel: "Quick filters",
  discoveryFilters: ["This season", "2 days", "Family", "Beach", "Mountain"],
  featureActionLabel: "View more",
  featureImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=80&auto=format&fit=crop",
  featureImageAlt: "Phu Quoc beach panorama preview",
  featureVrBadgeLabel: "360° VR",
  featureTitle: "Phu Quoc Beach Resort",
  featurePanoramaUrl: "https://dl.polyhaven.org/file/ph-assets/HDRIs/extra/Tonemapped%20JPG/secluded_beach.jpg",
  featureArticles: [
    {
      id: "article-sunset",
      title: "Bai Truong Sunset",
      kicker: "Guide",
      imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=420&q=82&auto=format&fit=crop",
      heroImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=2200&q=90&auto=format&fit=crop",
      panoramaUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=2200&q=90&auto=format&fit=crop",
      imageAlt: "Sunset over a Phu Quoc beach",
    },
    {
      id: "article-island-hop",
      title: "Southern Island Route",
      kicker: "Experience",
      imageUrl: "https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=420&q=82&auto=format&fit=crop",
      heroImageUrl: "https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=2200&q=90&auto=format&fit=crop",
      panoramaUrl: "https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=2200&q=90&auto=format&fit=crop",
      imageAlt: "Blue sea and island tour boat",
    },
    {
      id: "article-coral",
      title: "Coral Snorkeling",
      kicker: "Activity",
      imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=420&q=82&auto=format&fit=crop",
      heroImageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=2200&q=90&auto=format&fit=crop",
      panoramaUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=2200&q=90&auto=format&fit=crop",
      imageAlt: "Blue water for coral snorkeling",
    },
    {
      id: "article-seafood",
      title: "Beachfront Dinner",
      kicker: "Dining",
      imageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=420&q=82&auto=format&fit=crop",
      heroImageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=2200&q=90&auto=format&fit=crop",
      panoramaUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=2200&q=90&auto=format&fit=crop",
      imageAlt: "Dinner table near the coast",
    },
    {
      id: "article-resort",
      title: "Three-Day Resort Stay",
      kicker: "Itinerary",
      imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=420&q=82&auto=format&fit=crop",
      heroImageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=2200&q=90&auto=format&fit=crop",
      panoramaUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=2200&q=90&auto=format&fit=crop",
      imageAlt: "Beach resort with pool and palm trees",
    },
  ],
  detailBackLabel: "Back to destinations",
  detailCurrentViewLabel: "Current viewpoint",
  detailReviewLabel: "Traveler reviews",
  detailReviewSummary: "4.8/5 · 326 reviews",
  detailAddress: "Bai Truong, Phu Quoc, Kien Giang",
  detailSceneTitle: "Phu Quoc Beach Resort",
  detailRooms: [
    {
      id: "p1-lounge",
      name: "Lounge",
      panoramaUrl: "https://dl.polyhaven.org/file/ph-assets/HDRIs/extra/Tonemapped%20JPG/wooden_lounge.jpg",
      imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=160&q=75",
      imageAlt: "Airy lounge inside the Phu Quoc beachfront resort",
      thumbnailUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=160&q=75",
      summary: "A beachfront resort lounge with an airy first impression before moving into the suite, spa, and sunset terrace viewpoints.",
      hotspots: [
        { id: "h1", label: "Suite Room →", longitude: 110, latitude: 0, targetRoomId: "p1-bedroom" },
        { id: "h2", label: "Relaxation Corner →", longitude: -60, latitude: 0, targetRoomId: "p1-study" },
      ],
    },
    {
      id: "p1-bedroom",
      name: "Suite Room",
      panoramaUrl: "https://dl.polyhaven.org/file/ph-assets/HDRIs/extra/Tonemapped%20JPG/hotel_room.jpg",
      imageUrl: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=160&q=75",
      imageAlt: "Sea-view suite at the Phu Quoc resort",
      thumbnailUrl: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=160&q=75",
      summary: "A sea-view suite continuing the resort flow with premium stay cues and soft Bai Truong coastal light.",
      hotspots: [
        { id: "h3", label: "← Lounge", longitude: -70, latitude: 0, targetRoomId: "p1-lounge" },
        { id: "h4", label: "Spa Zone →", longitude: 90, latitude: 0, targetRoomId: "p1-bathroom" },
      ],
    },
    {
      id: "p1-bathroom",
      name: "Spa Zone",
      panoramaUrl: "https://dl.polyhaven.org/file/ph-assets/HDRIs/extra/Tonemapped%20JPG/modern_bathroom.jpg",
      imageUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=160&q=75",
      imageAlt: "Relaxing spa zone inside the beachfront resort",
      thumbnailUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=160&q=75",
      summary: "The spa keeps the Phu Quoc resort mood with clean light, soft materials, and a calm transition after the suite.",
      hotspots: [
        { id: "h5", label: "← Suite Room", longitude: -90, latitude: 0, targetRoomId: "p1-bedroom" },
      ],
    },
    {
      id: "p1-study",
      name: "Relaxation Corner",
      panoramaUrl: "https://dl.polyhaven.org/file/ph-assets/HDRIs/extra/Tonemapped%20JPG/blinds.jpg",
      imageUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=160&q=75",
      imageAlt: "Relaxation corner between the lounge and terrace viewpoint",
      thumbnailUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=160&q=75",
      summary: "A small-group relaxation viewpoint that keeps the beachfront resort rhythm before opening toward the sunset terrace.",
      hotspots: [
        { id: "h6", label: "← Lounge", longitude: 60, latitude: 0, targetRoomId: "p1-lounge" },
        { id: "h7", label: "Terrace View →", longitude: -120, latitude: 0, targetRoomId: "p1-terrace" },
      ],
    },
    {
      id: "p1-terrace",
      name: "Terrace View",
      panoramaUrl: "https://dl.polyhaven.org/file/ph-assets/HDRIs/extra/Tonemapped%20JPG/aft_lounge.jpg",
      imageUrl: "https://images.unsplash.com/photo-1600566753375-7a3b0e52c76c?w=160&q=75",
      imageAlt: "Sunset terrace facing the Phu Quoc sea",
      thumbnailUrl: "https://images.unsplash.com/photo-1600566753375-7a3b0e52c76c?w=160&q=75",
      summary: "The terrace closes the Phu Quoc route with a beachfront sunset viewpoint matching the original destination data.",
      hotspots: [
        { id: "h8", label: "← Relaxation Corner", longitude: 120, latitude: 0, targetRoomId: "p1-study" },
      ],
    },
  ],
  detailScenePickerLabel: "Choose viewpoint",
  detailPanelAriaLabel: "Destination details",
  detailViewerHint: "Drag to look around in 360° • scroll to zoom",
  detailLoadingLabel: "Loading 360° space",
  detailErrorLabel: "Unable to load the 360° scene",
  detailComments: [
    {
      id: "comment-1",
      author: "Minh Tran",
      role: "Local curator",
      rating: 5,
      body: "Bai Truong feels open and easy to read. The 360° viewpoint is wide enough to understand the resort layout before booking a visit.",
    },
  ],
  detailAutoRotateLabel: "Auto rotate",
  detailExpandLabel: "Expand details",
  detailCollapseLabel: "Collapse details",
  detailEnterFullscreenLabel: "Enter fullscreen",
  detailExitFullscreenLabel: "Exit fullscreen",
  detailCommentRatingLabel: "Your rating",
  detailCommentFormLabel: "Your comment",
  detailCommentFormPlaceholder: "Share what you noticed after viewing the 360° space...",
  detailCommentFormAction: "Post comment",
  detailFeedbackShowLabel: "Show reviews and comments",
  detailFeedbackHideLabel: "Hide reviews and comments",
  detailCommentAuthorName: "You",
  detailCommentAuthorRole: "Signed-in traveler",
};
